import {
  AcademicCapIcon, AdjustmentsIcon, AnnotationIcon, ArchiveIcon, ArrowCircleDownIcon,
  ArrowCircleLeftIcon, ArrowCircleRightIcon, ArrowCircleUpIcon, ArrowDownIcon, ArrowLeftIcon,
  ArrowNarrowDownIcon, ArrowNarrowLeftIcon, ArrowNarrowRightIcon, ArrowNarrowUpIcon, ArrowRightIcon,
  ArrowSmDownIcon, ArrowSmLeftIcon, ArrowSmRightIcon, ArrowSmUpIcon, ArrowUpIcon,
  ArrowsExpandIcon, AtSymbolIcon, BackspaceIcon, BadgeCheckIcon, BanIcon,
  BeakerIcon, BellIcon, BookOpenIcon, BookmarkAltIcon, BookmarkIcon,
  BriefcaseIcon, CakeIcon, CalculatorIcon, CalendarIcon, CameraIcon,
  CashIcon, ChartBarIcon, ChartPieIcon, ChartSquareBarIcon, ChatAlt2Icon,
  ChatAltIcon, ChatIcon, CheckCircleIcon, CheckIcon, ChevronDoubleDownIcon,
  ChevronDoubleLeftIcon, ChevronDoubleRightIcon, ChevronDoubleUpIcon, ChevronDownIcon, ChevronLeftIcon,
  ChevronRightIcon, ChevronUpIcon, ChipIcon, ClipboardCheckIcon, ClipboardCopyIcon,
  ClipboardListIcon, ClipboardIcon, ClockIcon, CloudDownloadIcon, CloudUploadIcon,
  CloudIcon, CodeIcon, CogIcon, CollectionIcon, ColorSwatchIcon,
  CreditCardIcon, CubeTransparentIcon, CubeIcon, CurrencyBangladeshiIcon, CurrencyDollarIcon,
  CurrencyEuroIcon, CurrencyPoundIcon, CurrencyRupeeIcon, CurrencyYenIcon, CursorClickIcon,
  DatabaseIcon, DesktopComputerIcon, DeviceMobileIcon, DeviceTabletIcon, DocumentAddIcon,
  DocumentDownloadIcon, DocumentDuplicateIcon, DocumentRemoveIcon, DocumentReportIcon, DocumentSearchIcon,
  DocumentTextIcon, DocumentIcon, DotsCircleHorizontalIcon, DotsHorizontalIcon, DotsVerticalIcon,
  DownloadIcon, DuplicateIcon, EmojiHappyIcon, EmojiSadIcon, ExclamationCircleIcon,
  ExclamationIcon, ExternalLinkIcon, EyeOffIcon, EyeIcon, FastForwardIcon,
  FilmIcon, FilterIcon, FingerPrintIcon, FireIcon, FlagIcon,
  FolderAddIcon, FolderDownloadIcon, FolderOpenIcon, FolderRemoveIcon, FolderIcon,
  GiftIcon, GlobeAltIcon, GlobeIcon, HandIcon, HashtagIcon,
  HeartIcon, HomeIcon, IdentificationIcon, InboxInIcon, InboxIcon,
  InformationCircleIcon, KeyIcon, LibraryIcon, LightBulbIcon, LightningBoltIcon,
  LinkIcon, LocationMarkerIcon, LockClosedIcon, LockOpenIcon, LoginIcon,
  LogoutIcon, MailOpenIcon, MailIcon, MapIcon, MenuAlt1Icon,
  MenuAlt2Icon, MenuAlt3Icon, MenuAlt4Icon, MenuIcon, MicrophoneIcon,
  MinusCircleIcon, MinusSmIcon, MinusIcon, MoonIcon, MusicNoteIcon,
  NewspaperIcon, OfficeBuildingIcon, PaperAirplaneIcon, PaperClipIcon, PauseIcon,
  PencilAltIcon, PencilIcon, PhoneIncomingIcon, PhoneMissedCallIcon, PhoneOutgoingIcon,
  PhoneIcon, PhotographIcon, PlayIcon, PlusCircleIcon, PlusSmIcon,
  PlusIcon, PresentationChartBarIcon, PresentationChartLineIcon, PrinterIcon, PuzzleIcon,
  QrcodeIcon, QuestionMarkCircleIcon, ReceiptRefundIcon, ReceiptTaxIcon, RefreshIcon,
  ReplyIcon, RewindIcon, RssIcon, SaveAsIcon, SaveIcon,
  ScaleIcon, ScissorsIcon, SearchCircleIcon, SearchIcon, SelectorIcon,
  ServerIcon, ShareIcon, ShieldCheckIcon, ShieldExclamationIcon, ShoppingBagIcon,
  ShoppingCartIcon, SortAscendingIcon, SortDescendingIcon, SparklesIcon, SpeakerphoneIcon,
  StarIcon, StatusOfflineIcon, StatusOnlineIcon, StopIcon, SunIcon,
  SupportIcon, SwitchHorizontalIcon, SwitchVerticalIcon, TableIcon, TagIcon,
  TemplateIcon, TerminalIcon, ThumbDownIcon, ThumbUpIcon, TicketIcon,
  TranslateIcon, TrashIcon, TrendingDownIcon, TrendingUpIcon, TruckIcon,
  UploadIcon, UserAddIcon, UserCircleIcon, UserGroupIcon, UserRemoveIcon,
  UserIcon, UsersIcon, VariableIcon, VideoCameraIcon, ViewBoardsIcon,
  ViewGridAddIcon, ViewGridIcon, ViewListIcon, VolumeOffIcon, VolumeUpIcon,
  WifiIcon, XCircleIcon, XIcon, ZoomInIcon, ZoomOutIcon } from "@heroicons/react/solid"

const Solid = {
  "academic-cap-solid": AcademicCapIcon,
  "adjustments-solid": AdjustmentsIcon,
  "annotation-solid": AnnotationIcon,
  "archive-solid": ArchiveIcon,
  "arrow-circle-down-solid": ArrowCircleDownIcon,
  "arrow-circle-left-solid": ArrowCircleLeftIcon,
  "arrow-circle-right-solid": ArrowCircleRightIcon,
  "arrow-circle-up-solid": ArrowCircleUpIcon,
  "arrow-down-solid": ArrowDownIcon,
  "arrow-left-solid": ArrowLeftIcon,
  "arrow-narrow-down-solid": ArrowNarrowDownIcon,
  "arrow-narrow-left-solid": ArrowNarrowLeftIcon,
  "arrow-narrow-right-solid": ArrowNarrowRightIcon,
  "arrow-narrow-up-solid": ArrowNarrowUpIcon,
  "arrow-right-solid": ArrowRightIcon,
  "arrow-sm-down-solid": ArrowSmDownIcon,
  "arrow-sm-left-solid": ArrowSmLeftIcon,
  "arrow-sm-right-solid": ArrowSmRightIcon,
  "arrow-sm-up-solid": ArrowSmUpIcon,
  "arrow-up-solid": ArrowUpIcon,
  "arrows-expand-solid": ArrowsExpandIcon,
  "at-symbol-solid": AtSymbolIcon,
  "backspace-solid": BackspaceIcon,
  "badge-check-solid": BadgeCheckIcon,
  "ban-solid": BanIcon,
  "beaker-solid": BeakerIcon,
  "bell-solid": BellIcon,
  "book-open-solid": BookOpenIcon,
  "bookmark-alt-solid": BookmarkAltIcon,
  "bookmark-solid": BookmarkIcon,
  "briefcase-solid": BriefcaseIcon,
  "cake-solid": CakeIcon,
  "calculator-solid": CalculatorIcon,
  "calendar-solid": CalendarIcon,
  "camera-solid": CameraIcon,
  "cash-solid": CashIcon,
  "chart-bar-solid": ChartBarIcon,
  "chart-pie-solid": ChartPieIcon,
  "chart-square-bar-solid": ChartSquareBarIcon,
  "chat-alt-2-solid": ChatAlt2Icon,
  "chat-alt-solid": ChatAltIcon,
  "chat-solid": ChatIcon,
  "check-circle-solid": CheckCircleIcon,
  "check-solid": CheckIcon,
  "chevron-double-down-solid": ChevronDoubleDownIcon,
  "chevron-double-left-solid": ChevronDoubleLeftIcon,
  "chevron-double-right-solid": ChevronDoubleRightIcon,
  "chevron-double-up-solid": ChevronDoubleUpIcon,
  "chevron-down-solid": ChevronDownIcon,
  "chevron-left-solid": ChevronLeftIcon,
  "chevron-right-solid": ChevronRightIcon,
  "chevron-up-solid": ChevronUpIcon,
  "chip-solid": ChipIcon,
  "clipboard-check-solid": ClipboardCheckIcon,
  "clipboard-copy-solid": ClipboardCopyIcon,
  "clipboard-list-solid": ClipboardListIcon,
  "clipboard-solid": ClipboardIcon,
  "clock-solid": ClockIcon,
  "cloud-download-solid": CloudDownloadIcon,
  "cloud-upload-solid": CloudUploadIcon,
  "cloud-solid": CloudIcon,
  "code-solid": CodeIcon,
  "cog-solid": CogIcon,
  "collection-solid": CollectionIcon,
  "color-swatch-solid": ColorSwatchIcon,
  "credit-card-solid": CreditCardIcon,
  "cube-transparent-solid": CubeTransparentIcon,
  "cube-solid": CubeIcon,
  "currency-bangladeshi-solid": CurrencyBangladeshiIcon,
  "currency-dollar-solid": CurrencyDollarIcon,
  "currency-euro-solid": CurrencyEuroIcon,
  "currency-pound-solid": CurrencyPoundIcon,
  "currency-rupee-solid": CurrencyRupeeIcon,
  "currency-yen-solid": CurrencyYenIcon,
  "cursor-click-solid": CursorClickIcon,
  "database-solid": DatabaseIcon,
  "desktop-computer-solid": DesktopComputerIcon,
  "device-mobile-solid": DeviceMobileIcon,
  "device-tablet-solid": DeviceTabletIcon,
  "document-add-solid": DocumentAddIcon,
  "document-download-solid": DocumentDownloadIcon,
  "document-duplicate-solid": DocumentDuplicateIcon,
  "document-remove-solid": DocumentRemoveIcon,
  "document-report-solid": DocumentReportIcon,
  "document-search-solid": DocumentSearchIcon,
  "document-text-solid": DocumentTextIcon,
  "document-solid": DocumentIcon,
  "dots-circle-horizontal-solid": DotsCircleHorizontalIcon,
  "dots-horizontal-solid": DotsHorizontalIcon,
  "dots-vertical-solid": DotsVerticalIcon,
  "download-solid": DownloadIcon,
  "duplicate-solid": DuplicateIcon,
  "emoji-happy-solid": EmojiHappyIcon,
  "emoji-sad-solid": EmojiSadIcon,
  "exclamation-circle-solid": ExclamationCircleIcon,
  "exclamation-solid": ExclamationIcon,
  "external-link-solid": ExternalLinkIcon,
  "eye-off-solid": EyeOffIcon,
  "eye-solid": EyeIcon,
  "fast-forward-solid": FastForwardIcon,
  "film-solid": FilmIcon,
  "filter-solid": FilterIcon,
  "finger-print-solid": FingerPrintIcon,
  "fire-solid": FireIcon,
  "flag-solid": FlagIcon,
  "folder-add-solid": FolderAddIcon,
  "folder-download-solid": FolderDownloadIcon,
  "folder-open-solid": FolderOpenIcon,
  "folder-remove-solid": FolderRemoveIcon,
  "folder-solid": FolderIcon,
  "gift-solid": GiftIcon,
  "globe-alt-solid": GlobeAltIcon,
  "globe-solid": GlobeIcon,
  "hand-solid": HandIcon,
  "hashtag-solid": HashtagIcon,
  "heart-solid": HeartIcon,
  "home-solid": HomeIcon,
  "identification-solid": IdentificationIcon,
  "inbox-in-solid": InboxInIcon,
  "inbox-solid": InboxIcon,
  "information-circle-solid": InformationCircleIcon,
  "key-solid": KeyIcon,
  "library-solid": LibraryIcon,
  "light-bulb-solid": LightBulbIcon,
  "lightning-bolt-solid": LightningBoltIcon,
  "link-solid": LinkIcon,
  "location-marker-solid": LocationMarkerIcon,
  "lock-closed-solid": LockClosedIcon,
  "lock-open-solid": LockOpenIcon,
  "login-solid": LoginIcon,
  "logout-solid": LogoutIcon,
  "mail-open-solid": MailOpenIcon,
  "mail-solid": MailIcon,
  "map-solid": MapIcon,
  "menu-alt-1-solid": MenuAlt1Icon,
  "menu-alt-2-solid": MenuAlt2Icon,
  "menu-alt-3-solid": MenuAlt3Icon,
  "menu-alt-4-solid": MenuAlt4Icon,
  "menu-solid": MenuIcon,
  "microphone-solid": MicrophoneIcon,
  "minus-circle-solid": MinusCircleIcon,
  "minus-sm-solid": MinusSmIcon,
  "minus-solid": MinusIcon,
  "moon-solid": MoonIcon,
  "music-note-solid": MusicNoteIcon,
  "newspaper-solid": NewspaperIcon,
  "office-building-solid": OfficeBuildingIcon,
  "paper-airplane-solid": PaperAirplaneIcon,
  "paper-clip-solid": PaperClipIcon,
  "pause-solid": PauseIcon,
  "pencil-alt-solid": PencilAltIcon,
  "pencil-solid": PencilIcon,
  "phone-incoming-solid": PhoneIncomingIcon,
  "phone-missed-call-solid": PhoneMissedCallIcon,
  "phone-outgoing-solid": PhoneOutgoingIcon,
  "phone-solid": PhoneIcon,
  "photograph-solid": PhotographIcon,
  "play-solid": PlayIcon,
  "plus-circle-solid": PlusCircleIcon,
  "plus-sm-solid": PlusSmIcon,
  "plus-solid": PlusIcon,
  "presentation-chart-bar-solid": PresentationChartBarIcon,
  "presentation-chart-line-solid": PresentationChartLineIcon,
  "printer-solid": PrinterIcon,
  "puzzle-solid": PuzzleIcon,
  "qrcode-solid": QrcodeIcon,
  "question-mark-circle-solid": QuestionMarkCircleIcon,
  "receipt-refund-solid": ReceiptRefundIcon,
  "receipt-tax-solid": ReceiptTaxIcon,
  "refresh-solid": RefreshIcon,
  "reply-solid": ReplyIcon,
  "rewind-solid": RewindIcon,
  "rss-solid": RssIcon,
  "save-as-solid": SaveAsIcon,
  "save-solid": SaveIcon,
  "scale-solid": ScaleIcon,
  "scissors-solid": ScissorsIcon,
  "search-circle-solid": SearchCircleIcon,
  "search-solid": SearchIcon,
  "selector-solid": SelectorIcon,
  "server-solid": ServerIcon,
  "share-solid": ShareIcon,
  "shield-check-solid": ShieldCheckIcon,
  "shield-exclamation-solid": ShieldExclamationIcon,
  "shopping-bag-solid": ShoppingBagIcon,
  "shopping-cart-solid": ShoppingCartIcon,
  "sort-ascending-solid": SortAscendingIcon,
  "sort-descending-solid": SortDescendingIcon,
  "sparkles-solid": SparklesIcon,
  "speakerphone-solid": SpeakerphoneIcon,
  "star-solid": StarIcon,
  "status-offline-solid": StatusOfflineIcon,
  "status-online-solid": StatusOnlineIcon,
  "stop-solid": StopIcon,
  "sun-solid": SunIcon,
  "support-solid": SupportIcon,
  "switch-horizontal-solid": SwitchHorizontalIcon,
  "switch-vertical-solid": SwitchVerticalIcon,
  "table-solid": TableIcon,
  "tag-solid": TagIcon,
  "template-solid": TemplateIcon,
  "terminal-solid": TerminalIcon,
  "thumb-up-solid": ThumbUpIcon,
  "thumb-down-solid": ThumbDownIcon,
  "ticket-solid": TicketIcon,
  "translate-solid": TranslateIcon,
  "trash-solid": TrashIcon,
  "trending-down-solid": TrendingDownIcon,
  "trending-up-solid": TrendingUpIcon,
  "truck-solid": TruckIcon,
  "upload-solid": UploadIcon,
  "user-add-solid": UserAddIcon,
  "user-circle-solid": UserCircleIcon,
  "user-group-solid": UserGroupIcon,
  "user-remove-solid": UserRemoveIcon,
  "user-solid": UserIcon,
  "users-solid": UsersIcon,
  "variable-solid": VariableIcon,
  "video-camera-solid": VideoCameraIcon,
  "view-boards-solid": ViewBoardsIcon,
  "view-grid-add-solid": ViewGridAddIcon,
  "view-grid-solid": ViewGridIcon,
  "view-list-solid": ViewListIcon,
  "volume-off-solid": VolumeOffIcon,
  "volume-up-solid": VolumeUpIcon,
  "wifi-solid": WifiIcon,
  "x-circle-solid": XCircleIcon,
  "x-solid": XIcon,
  "zoom-in-solid": ZoomInIcon,
  "zoom-out-solid": ZoomOutIcon
}

export {
  Solid
}