import React from "react";
import cx from "clsx";
import { AcademicCapIcon, AdjustmentsIcon, AnnotationIcon, ArchiveIcon, ArrowCircleDownIcon,
ArrowCircleLeftIcon, ArrowCircleRightIcon, ArrowCircleUpIcon, ArrowDownIcon, ArrowLeftIcon,
ArrowNarrowDownIcon, ArrowNarrowLeftIcon, ArrowNarrowRightIcon, ArrowNarrowUpIcon, ArrowRightIcon,
ArrowSmDownIcon, ArrowSmLeftIcon, ArrowSmRightIcon, ArrowSmUpIcon, ArrowUpIcon,
ArrowsExpandIcon, AtSymbolIcon, BackspaceIcon, BadgeCheckIcon, BanIcon,
BeakerIcon, BellIcon, BookOpenIcon, BookmarkAltIcon, BookmarkIcon,
BriefcaseIcon, CakeIcon, CalculatorIcon, CalendarIcon, CameraIcon,
CashIcon, ChartBarIcon, ChartPieIcon, ChartSquareBarIcon, ChatAlt2Icon,
ChatAltIcon, ChatIcon, CheckCircleIcon, CheckIcon, ChevronDoubleDownIcon,
ChevronDoubleLeftIcon, ChevronDoubleRightIcon, ChevronDoubleUpIcon, ChevronDownIcon, ChevronLeftIcon,
ChevronRightIcon, ChevronUpIcon, ChipIcon, ClipboardCheckIcon, ClipboardCopyIcon,
ClipboardListIcon, ClipboardIcon, ClockIcon, CloudDownloadIcon, CloudUploadIcon,
CloudIcon, CodeIcon, CogIcon, CollectionIcon, ColorSwatchIcon,
CreditCardIcon, CubeTransparentIcon, CubeIcon, CurrencyBangladeshiIcon, CurrencyDollarIcon,
CurrencyEuroIcon, CurrencyPoundIcon, CurrencyRupeeIcon, CurrencyYenIcon, CursorClickIcon,
DatabaseIcon, DesktopComputerIcon, DeviceMobileIcon, DeviceTabletIcon, DocumentAddIcon,
DocumentDownloadIcon, DocumentDuplicateIcon, DocumentRemoveIcon, DocumentReportIcon, DocumentSearchIcon,
DocumentTextIcon, DocumentIcon, DotsCircleHorizontalIcon, DotsHorizontalIcon, DotsVerticalIcon,
DownloadIcon, DuplicateIcon, EmojiHappyIcon, EmojiSadIcon, ExclamationCircleIcon,
ExclamationIcon, ExternalLinkIcon, EyeOffIcon, EyeIcon, FastForwardIcon,
FilmIcon, FilterIcon, FingerPrintIcon, FireIcon, FlagIcon,
FolderAddIcon, FolderDownloadIcon, FolderOpenIcon, FolderRemoveIcon, FolderIcon,
GiftIcon, GlobeAltIcon, GlobeIcon, HandIcon, HashtagIcon,
HeartIcon, HomeIcon, IdentificationIcon, InboxInIcon, InboxIcon,
InformationCircleIcon, KeyIcon, LibraryIcon, LightBulbIcon, LightningBoltIcon,
LinkIcon, LocationMarkerIcon, LockClosedIcon, LockOpenIcon, LoginIcon,
LogoutIcon, MailOpenIcon, MailIcon, MapIcon, MenuAlt1Icon,
MenuAlt2Icon, MenuAlt3Icon, MenuAlt4Icon, MenuIcon, MicrophoneIcon,
MinusCircleIcon, MinusSmIcon, MinusIcon, MoonIcon, MusicNoteIcon,
NewspaperIcon, OfficeBuildingIcon, PaperAirplaneIcon, PaperClipIcon, PauseIcon,
PencilAltIcon, PencilIcon, PhoneIncomingIcon, PhoneMissedCallIcon, PhoneOutgoingIcon,
PhoneIcon, PhotographIcon, PlayIcon, PlusCircleIcon, PlusSmIcon,
PlusIcon, PresentationChartBarIcon, PresentationChartLineIcon, PrinterIcon, PuzzleIcon,
QrcodeIcon, QuestionMarkCircleIcon, ReceiptRefundIcon, ReceiptTaxIcon, RefreshIcon,
ReplyIcon, RewindIcon, RssIcon, SaveAsIcon, SaveIcon,
ScaleIcon, ScissorsIcon, SearchCircleIcon, SearchIcon, SelectorIcon,
ServerIcon, ShareIcon, ShieldCheckIcon, ShieldExclamationIcon, ShoppingBagIcon,
ShoppingCartIcon, SortAscendingIcon, SortDescendingIcon, SparklesIcon, SpeakerphoneIcon,
StarIcon, StatusOfflineIcon, StatusOnlineIcon, StopIcon, SunIcon,
SupportIcon, SwitchHorizontalIcon, SwitchVerticalIcon, TableIcon, TagIcon,
TemplateIcon, TerminalIcon, ThumbDownIcon, ThumbUpIcon, TicketIcon,
TranslateIcon, TrashIcon, TrendingDownIcon, TrendingUpIcon, TruckIcon,
UploadIcon, UserAddIcon, UserCircleIcon, UserGroupIcon, UserRemoveIcon,
UserIcon, UsersIcon, VariableIcon, VideoCameraIcon, ViewBoardsIcon,
ViewGridAddIcon, ViewGridIcon, ViewListIcon, VolumeOffIcon, VolumeUpIcon,
WifiIcon, XCircleIcon, XIcon, ZoomInIcon, ZoomOutIcon } from "@heroicons/react/outline"
import PropTypes from "prop-types";

import { Palletes, Color, Contrast } from "../../utils/color";

const sizes = {
  xs: "h-2",
  sm: "h-4",
  md: "h-10",
  lg: "h-20",
  xlg: "h-32"
}

const icons = {
  "academic-cap": AcademicCapIcon,
  "adjustments": AdjustmentsIcon,
  "annotation": AnnotationIcon,
  "archive": ArchiveIcon,
  "arrow-circle-down": ArrowCircleDownIcon,
  "arrow-circle-left": ArrowCircleLeftIcon,
  "arrow-circle-right": ArrowCircleRightIcon,
  "arrow-circle-up": ArrowCircleUpIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-narrow-down": ArrowNarrowDownIcon,
  "arrow-narrow-left": ArrowNarrowLeftIcon,
  "arrow-narrow-right": ArrowNarrowRightIcon,
  "arrow-narrow-up": ArrowNarrowUpIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-sm-down": ArrowSmDownIcon,
  "arrow-sm-left": ArrowSmLeftIcon,
  "arrow-sm-right": ArrowSmRightIcon,
  "arrow-sm-up": ArrowSmUpIcon,
  "arrow-up": ArrowUpIcon,
  "arrows-expand": ArrowsExpandIcon,
  "at-symbol": AtSymbolIcon,
  "backspace": BackspaceIcon,
  "badge-check": BadgeCheckIcon,
  "ban": BanIcon,
  "beaker": BeakerIcon,
  "bell": BellIcon,
  "book-open": BookOpenIcon,
  "bookmark-alt": BookmarkAltIcon,
  "bookmark": BookmarkIcon,
  "briefcase": BriefcaseIcon,
  "cake": CakeIcon,
  "calculator": CalculatorIcon,
  "calendar": CalendarIcon,
  "camera": CameraIcon,
  "cash": CashIcon,
  "chart-bar": ChartBarIcon,
  "chart-pie": ChartPieIcon,
  "chart-square-bar": ChartSquareBarIcon,
  "chat-alt-2": ChatAlt2Icon,
  "chat-alt": ChatAltIcon,
  "chat": ChatIcon,
  "check-circle": CheckCircleIcon,
  "check": CheckIcon,
  "chevron-double-down": ChevronDoubleDownIcon,
  "chevron-double-left": ChevronDoubleLeftIcon,
  "chevron-double-right": ChevronDoubleRightIcon,
  "chevron-double-up": ChevronDoubleUpIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  "chip": ChipIcon,
  "clipboard-check": ClipboardCheckIcon,
  "clipboard-copy": ClipboardCopyIcon,
  "clipboard-list": ClipboardListIcon,
  "clipboard": ClipboardIcon,
  "clock": ClockIcon,
  "cloud-download": CloudDownloadIcon,
  "cloud-upload": CloudUploadIcon,
  "cloud": CloudIcon,
  "code": CodeIcon,
  "cog": CogIcon,
  "collection": CollectionIcon,
  "color-swatch": ColorSwatchIcon,
  "credit-card": CreditCardIcon,
  "cube-transparent": CubeTransparentIcon,
  "cube": CubeIcon,
  "currency-bangladeshi": CurrencyBangladeshiIcon,
  "currency-dollar": CurrencyDollarIcon,
  "currency-euro": CurrencyEuroIcon,
  "currency-pound": CurrencyPoundIcon,
  "currency-rupee": CurrencyRupeeIcon,
  "currency-yen": CurrencyYenIcon,
  "cursor-click": CursorClickIcon,
  "database": DatabaseIcon,
  "desktop-computer": DesktopComputerIcon,
  "device-mobile": DeviceMobileIcon,
  "device-tablet": DeviceTabletIcon,
  "document-add": DocumentAddIcon,
  "document-download": DocumentDownloadIcon,
  "document-duplicate": DocumentDuplicateIcon,
  "document-remove": DocumentRemoveIcon,
  "document-report": DocumentReportIcon,
  "document-search": DocumentSearchIcon,
  "document-text": DocumentTextIcon,
  "document": DocumentIcon,
  "dots-circle-horizontal": DotsCircleHorizontalIcon,
  "dots-horizontal": DotsHorizontalIcon,
  "dots-vertical": DotsVerticalIcon,
  "download": DownloadIcon,
  "duplicate": DuplicateIcon,
  "emoji-happy": EmojiHappyIcon,
  "emoji-sad": EmojiSadIcon,
  "exclamation-circle": ExclamationCircleIcon,
  "exclamation": ExclamationIcon,
  "external-link": ExternalLinkIcon,
  "eye-off": EyeOffIcon,
  "eye": EyeIcon,
  "fast-forward": FastForwardIcon,
  "film": FilmIcon,
  "filter": FilterIcon,
  "finger-print": FingerPrintIcon,
  "fire": FireIcon,
  "flag": FlagIcon,
  "folder-add": FolderAddIcon,
  "folder-download": FolderDownloadIcon,
  "folder-open": FolderOpenIcon,
  "folder-remove": FolderRemoveIcon,
  "folder": FolderIcon,
  "gift": GiftIcon,
  "globe-alt": GlobeAltIcon,
  "globe": GlobeIcon,
  "hand": HandIcon,
  "hashtag": HashtagIcon,
  "heart": HeartIcon,
  "home": HomeIcon,
  "identification": IdentificationIcon,
  "inbox-in": InboxInIcon,
  "inbox": InboxIcon,
  "information-circle": InformationCircleIcon,
  "key": KeyIcon,
  "library": LibraryIcon,
  "light-bulb": LightBulbIcon,
  "lightning-bolt": LightningBoltIcon,
  "link": LinkIcon,
  "location-marker": LocationMarkerIcon,
  "lock-closed": LockClosedIcon,
  "lock-open": LockOpenIcon,
  "login": LoginIcon,
  "logout": LogoutIcon,
  "mail-open": MailOpenIcon,
  "mail": MailIcon,
  "map": MapIcon,
  "menu-alt-1": MenuAlt1Icon,
  "menu-alt-2": MenuAlt2Icon,
  "menu-alt-3": MenuAlt3Icon,
  "menu-alt-4": MenuAlt4Icon,
  "menu": MenuIcon,
  "microphone": MicrophoneIcon,
  "minus-circle": MinusCircleIcon,
  "minus-sm": MinusSmIcon,
  "minus": MinusIcon,
  "moon": MoonIcon,
  "music-note": MusicNoteIcon,
  "newspaper": NewspaperIcon,
  "office-building": OfficeBuildingIcon,
  "paper-airplane": PaperAirplaneIcon,
  "paper-clip": PaperClipIcon,
  "pause": PauseIcon,
  "pencil-alt": PencilAltIcon,
  "pencil": PencilIcon,
  "phone-incoming": PhoneIncomingIcon,
  "phone-missed-call": PhoneMissedCallIcon,
  "phone-outgoing": PhoneOutgoingIcon,
  "phone": PhoneIcon,
  "photograph": PhotographIcon,
  "play": PlayIcon,
  "plus-circle": PlusCircleIcon,
  "plus-sm": PlusSmIcon,
  "plus": PlusIcon,
  "presentation-chart-bar": PresentationChartBarIcon,
  "presentation-chart-line": PresentationChartLineIcon,
  "printer": PrinterIcon,
  "puzzle": PuzzleIcon,
  "qrcode": QrcodeIcon,
  "question-mark-circle": QuestionMarkCircleIcon,
  "receipt-refund": ReceiptRefundIcon,
  "receipt-tax": ReceiptTaxIcon,
  "refresh": RefreshIcon,
  "reply": ReplyIcon,
  "rewind": RewindIcon,
  "rss": RssIcon,
  "save-as": SaveAsIcon,
  "save": SaveIcon,
  "scale": ScaleIcon,
  "scissors": ScissorsIcon,
  "search-circle": SearchCircleIcon,
  "search": SearchIcon,
  "selector": SelectorIcon,
  "server": ServerIcon,
  "share": ShareIcon,
  "shield-check": ShieldCheckIcon,
  "shield-exclamation": ShieldExclamationIcon,
  "shopping-bag": ShoppingBagIcon,
  "shopping-cart": ShoppingCartIcon,
  "sort-ascending": SortAscendingIcon,
  "sort-descending": SortDescendingIcon,
  "sparkles": SparklesIcon,
  "speakerphone": SpeakerphoneIcon,
  "star": StarIcon,
  "status-offline": StatusOfflineIcon,
  "status-online": StatusOnlineIcon,
  "stop": StopIcon,
  "sun": SunIcon,
  "support": SupportIcon,
  "switch-horizontal": SwitchHorizontalIcon,
  "switch-vertical": SwitchVerticalIcon,
  "table": TableIcon,
  "tag": TagIcon,
  "template": TemplateIcon,
  "terminal": TerminalIcon,
  "thumb-up": ThumbUpIcon,
  "thumb-down": ThumbDownIcon,
  "ticket": TicketIcon,
  "translate": TranslateIcon,
  "trash": TrashIcon,
  "trending-down": TrendingDownIcon,
  "trending-up": TrendingUpIcon,
  "truck": TruckIcon,
  "upload": UploadIcon,
  "user-add": UserAddIcon,
  "user-circle": UserCircleIcon,
  "user-group": UserGroupIcon,
  "user-remove": UserRemoveIcon,
  "user": UserIcon,
  "users": UsersIcon,
  "variable": VariableIcon,
  "video-camera": VideoCameraIcon,
  "view-boards": ViewBoardsIcon,
  "view-grid-add": ViewGridAddIcon,
  "view-grid": ViewGridIcon,
  "view-list": ViewListIcon,
  "volume-off": VolumeOffIcon,
  "volume-up": VolumeUpIcon,
  "wifi": WifiIcon,
  "x-circle": XCircleIcon,
  "x": XIcon,
  "zoom-in": ZoomInIcon,
  "zoom-out": ZoomOutIcon
}

const Icon = ({ icon, size, color, contrast, className,
  mt, mb, ml, mr }) => {
  const IconElem = icons[icon]

  const baseClasses = cx(
    className !== undefined && className,
    sizes[size],
    Color("text", color, contrast),
    mt !== undefined && `mt-${mt}`,
    mb !== undefined && `mb-${mb}`,
    ml !== undefined && `ml-${ml}`,
    mr !== undefined && `mr-${mr}`,
  )

  return(
    <IconElem className={baseClasses} />
  )
}

Icon.propTypes = {
  icon: PropTypes.oneOf(Object.keys(icons)),
  size: PropTypes.oneOf(Object.keys(sizes)),
  color: PropTypes.oneOf(Palletes),
  contrast: PropTypes.oneOf(Contrast),
  className: PropTypes.string,
  mt: PropTypes.number,
  mb: PropTypes.number,
  ml: PropTypes.number,
  mr: PropTypes.number,
}

Icon.defaultProps = {
  size: "sm",
  contrast: 600
}

Icon.Solid = icons;

export default Icon;
